*** Variables ***
${home_locator.icn_cart}        xpath=//a[@class="shopping_cart_link"]
${home_locator.icn_menu}        xpath=//button[@id="react-burger-menu-btn"]
${home_locator.ddl_filter_menu}        xpath=//select[@class="product_sort_container"]
${home_locator.ddl_filter}        xpath=//select[@class="product_sort_container"]
${home_locator.lbl_title_header}        xpath=//span[@class="title"]
${home_locator.list_of_product}        xpath=//div[@class="inventory_item"]
${home_locator.lbl_sub_menu_name}        xpath=//a[text()="***lbl_sub_menu***"]
${home_locator.icn_close_sub_menu}        xpath=//button[@id="react-burger-cross-btn"]
${home_locator.lbl_filter_menu_name}        xpath=//option[text()="***lbl_filter_menu_name***"]
${home_locator.lbl_footer_page}        xpath=//div[text()="${lbl_footer_page}"]
${home_locator.lbl_product_name}        xpath=//div[@class="inventory_item_name " and text()="***lbl_product_name***"]
${home_page.btn_add_product}        xpath=//div[@data-test="inventory-item-name" and text()="***product_name***"] /ancestor::div[@class="inventory_item"]//button[text()="Add to cart"]
${home_page.btn_remove_product}        xpath=//div[@data-test="inventory-item-name" and text()="***product_name***"] /ancestor::div[@class="inventory_item"]//button[text()="Remove"]
${home_page.btn_count_of_products}        xpath=//span[@class="shopping_cart_badge" and text()="***count_of_products***"]
${home_page.lbl_price_of_products}        xpath=//div[@data-test="inventory-item-name" and text()="***product_name***"]/ancestor::div[@class="inventory_item"]//div[@data-test="inventory-item-price"]
