*** Variables ***
${home_locator.icn_cart}        xpath=//a[@class="shopping_cart_link"]
${home_locator.icn_menu}        xpath=//button[@id="react-burger-menu-btn"]
${home_locator.ddl_filter_menu}        xpath=//select[@class="product_sort_container"]
${home_locator.ddl_filter}        xpath=//select[@class="product_sort_container"]
${home_locator.lbl_title_header}        xpath=//span[@class="title"]
${home_locator.list_of_product}        xpath=//div[@class="inventory_item"]
${home_locator.lbl_sub_menu_name}        xpath=//a[text()="***lbl_sub_menu***"]
${home_locator.icn_close_sub_menu}        xpath=//button[@id="react-burger-cross-btn"]
${home_locator.lbl_filter_menu_name}        xpath=//option[text()="***lbl_filter_menu_name***"]
${home_locator.lbl_footer_page}        xpath=//div[text()="${lbl_footer_page}"]
